name: pygsheets_n_gdrive
dependencies:
- backports=1.0=py27_1
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports_abc=0.5=py27_0
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- decorator=4.1.2=py27_0
- enum34=1.1.6=py27_1
- ipykernel=4.6.1=py27_0
- ipython=5.5.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- libsodium=1.0.10=0
- ncurses=5.9=10
- numpy=1.13.3=py27_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandas=0.21.0=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- python=2.7.14=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.3=py_1
- pyzmq=16.0.2=py27_2
- readline=6.2=0
- scandir=1.6=py27_0
- setuptools=36.6.0=py27_1
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.11.0=py27_1
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_1
- tk=8.5.19=2
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.30.0=py_1
- zeromq=4.2.1=1
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - google-api-python-client==1.6.4
  - httplib2==0.10.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - oauth2client==4.1.2
  - prompt-toolkit==1.0.15
  - pyasn1==0.3.7
  - pyasn1-modules==0.1.5
  - pygsheets==1.1.3
  - rsa==3.4.2
  - uritemplate==3.0.0

